"""add role and password hash column to user table

Revision ID: eb633f176f5c
Revises: 85e1638553c2
Create Date: 2026-08-16 22:09:27.397251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb633f176f5c'
down_revision = '85e1638553c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), server_default='user', nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), server_default='passwordhas123', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
